version: '3'
services:
  rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"
    network_mode: host
  worker:
    build: .
    image: &img worker
    command: [celery, worker, --concurrency=20, --app=scraper, --loglevel=INFO]
    depends_on:
      - rabbit
      - beat
    restart: on-failure
    volumes:
      - .:/code/
    network_mode: host
  beat:
    build: .
    image: *img
    command: [celery, beat, --app=scraper, --loglevel=INFO]
    depends_on:
      - rabbit
    restart: on-failure
    volumes:
      - .:/code/
    network_mode: host
