version: '3'

networks:
  lan:


services:
  rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"
  worker:
    build: .
    links:
      - rabbit
    depends_on:
      - rabbit
    restart: on-failure
  hworker1:
    build:
      context: ./
      dockerfile: hworkerDF
    environment:
      - STH=sth
    ports:
      - 1080:1080
    command: /bin/zsh
