version: '3'

services:
  hworker78:
    build:
      context: ./
      dockerfile: hworkerDF2
    environment:
      - cypara_j=1
    network_mode: "host"
    restart: always
    command: zsh cyrefresh.zsh 78 78

  hworker77:
    build:
      context: ./
      dockerfile: hworkerDF2
    environment:
      - cypara_j=2
    network_mode: "host"
    restart: always
    command: zsh cyrefresh.zsh 77 77

  hworker0_50_a:
    build:
      context: ./
      dockerfile: hworkerDF2
    environment:
      - cypara_j=6
    network_mode: "host"
    restart: always
    command: zsh cyrefresh.zsh 0 50

  hworker51_100_a:
    build:
      context: ./
      dockerfile: hworkerDF2
    environment:
      - cypara_j=6
    network_mode: "host"
    restart: always
    command: zsh cyrefresh.zsh 51 100
